#ifndef HAND_CONTROLLER_CONFIG_H
#define HAND_CONTROLLER_CONFIG_H

#define HC_SPEED_POT A0
#define BUTTON_UP 9
#define BUTTON_DOWN 10
#define BUTTONS_CHECK_DELAY_MINSPEED 80
#define BUTTONS_CHECK_DELAY_MAXSPEED 20
#define MAX_STEPS_PUSH 60
#define MOTOR_HC_RPM_MAX 500
#define MOTOR_HC_RPM_MIN 2

#endif
